# This file configures GitHub Actions to build and deploy your Flutter web app to Firebase Hosting when changes are pushed to the main branch.

name: Deploy Flutter Web App to Firebase Hosting on merge

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Set up Java (required for Flutter)
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '11'

      # Step 3: Cache Flutter SDK
      - name: Cache Flutter SDK
        uses: actions/cache@v3
        with:
          path: ~/.flutter
          key: ${{ runner.os }}-flutter-sdk-${{ hashFiles('**/pubspec.yaml') }}
          restore-keys: |
            ${{ runner.os }}-flutter-sdk-

      # Step 4: Install Flutter SDK
      - name: Install Flutter SDK
        run: |
          git clone https://github.com/flutter/flutter.git -b stable --depth 1
          echo "$PWD/flutter/bin" >> $GITHUB_PATH

      # Step 5: Run Flutter Doctor
      - name: Run Flutter Doctor
        run: flutter doctor -v

      # Step 6: Install Dependencies
      - name: Install Dependencies
        run: flutter pub get

      # Step 7: Build Flutter Web App
      - name: Build Flutter Web App
        run: flutter build web --release

      # Step 8: Deploy to Firebase Hosting
      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_BEZIER_CURVE_SCICOMP }}'
          channelId: live
          projectId: 'bezier-curve-scicomp'
          target: 'default'
        env:
          FIREBASE_CLI_PREVIEWS: hostingchannels
          FIREBASE_CLI_JSON_OUTPUT: true
